apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{$.Values.acme.email}}
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          cloudflare:
            email: {{$.Values.cloudflare.email}}
            apiTokenSecretRef:
              name: cloudflare-api-key-secret
              key: api-key
