image:
  repository: eu-amsterdam-1.ocir.io/axpksneljs3y/nvd-codes/web
  tag: 2c692817b9b6c96b840982a066922c7662ec3914

container:
  envFrom:
    - secretRef:
        name: nvd-codes-web
  healthCheck: /api/healthz

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.tls: "true"
  path: /
  pathType: Prefix
  tls:
    - hosts:
        - nvd.codes
      secretName: nvd-codes-web
  hosts:
    - nvd.codes

