image:
  repository: eu-amsterdam-1.ocir.io/axpksneljs3y/nvd-codes/web
  tag: 03f27a90bf9f0580b45a21a36b163ec2790b1e2b

replicas: 2

container:
  envFrom:
    - secretRef:
        name: nvd-codes-web
  healthCheck: /api/healthz

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.tls: "true"
  path: /
  pathType: Prefix
  tls:
    - hosts:
        - nvd.codes
      secretName: nvd-codes-web
  hosts:
    - nvd.codes

middleware:
  - name: set-security-headers
    spec:
      headers:
        customResponseHeaders:
          X-Powered-By: "Passion and tiny cute kittens"
          X-nananana: "Batcache"
        contentTypeNosniff: true
        frameDeny: true
        browserXssFilter: true
        sslRedirect: true
        stsSeconds: 31536000
        referrerPolicy: strict-origin-when-cross-origin
