version: "3.4"
services:

  ui:
    build:
      dockerfile: docker/Dockerfile.gatsby
      context: .
    command: yarn develop --host=0.0.0.0
    environment:
      CONTENT_FOLDER: /content
      GATSBY_PROJECT_API: http://localhost:7000
    volumes:
      - ./content:/content
      - ./src:/app/src
      - ./gatsby-browser.js:/app/gatsby-browser.js
      - ./gatsby-config.js:/app/gatsby-config.js
      - ./gatsby-node.js:/app/gatsby-node.js
      - ./tsconfig.json:/app/tsconfig.json
    ports:
      - "5000:8000"

  proxy:
    build:
      dockerfile: docker/Dockerfile.functions
      context: .
    command: func start --dotnet --cors http://localhost:5000
    environment:
      AZURE_FUNCTION_PROXY_DISABLE_LOCAL_CALL: "true"
      AzureWebJobsStorage: "UseDevelopmentStorage=true"
      FUNCTIONS_WORKER_RUNTIME: dotnet
      PROJECT_API: http://project:7071
    volumes:
      - ./functions/Proxy:/app
    ports:
      - "7000:7071"

  project:
    build:
      dockerfile: docker/Dockerfile.functions
      context: .
    command: func start --dotnet
    environment:
      AzureWebJobsStorage: "UseDevelopmentStorage=true"
      FUNCTIONS_WORKER_RUNTIME: dotnet
    secrets:
      - GITHUB_TOKEN
    volumes:
      - ./functions/ProjectsApi:/app
    ports:
      - "7001:7071"

secrets:
  GITHUB_TOKEN:
    file: .secrets/github_token
