image:
  repository: eu-amsterdam-1.ocir.io/axpksneljs3y/nvd-codes/blog
  tag: 23b2560ff7b827ea0dd1eb6568194ae2c90ab12a

container:
  env:
    - name: LOG_LEVEL
      value: "info"
  envFrom:
    - secretRef:
        name: nvd-codes-blog
  volumeMounts:
    - name: wallet
      mountPath: "/wallet"
      readOnly: true

volumes:
  - name: wallet
    secret:
      secretName: nvd-codes-db-wallet

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.tls: "true"
  path: /blog
  pathType: Prefix
  tls:
    - hosts:
        - api.nvd.codes
      secretName: nvd-codes-api
  hosts:
    - api.nvd.codes

middleware:
  - name: set-cors-headers
    spec:
      headers:
        accessControlAllowOriginList:
          - "https://nvd.codes"
        accessControlMaxAge: 100
        addVaryHeader: true
