{{- if .Values.ingress.enabled -}}
{{- $fullName := include "app.name" . -}}
{{- $name := include "app.name" . -}}
{{- $chartName := include "app.chart" . -}}
{{- $ingressPath := .Values.ingress.path -}}
{{- $middleware := .Values.middleware -}}
{{- $middlewareAnnotations := include "middleware.annotate" .}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName}}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{.Release.Name}}
    app.kubernetes.io/managed-by: {{.Release.Service}}
    helm.sh/chart: {{ $chartName }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    {{- if $middleware }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ $middlewareAnnotations }}
    {{- end}}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: {{ $ingressPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: http
  {{- end }}
{{- end }}
