{{- if .Values.middleware }}
{{- $appName := include "app.name" . -}}
{{- range .Values.middleware}}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ $appName }}-{{.name}}
spec: {{ .spec | toYaml | nindent 2}}
{{- end}}
{{- end }}
