kind: Service
apiVersion: v1
metadata:
  name: {{include "app.name" .}}
  labels:
    app.kubernetes.io/name: {{include "app.name" .}}
    app.kubernetes.io/instance: {{.Release.Name}}
    app.kubernetes.io/managed-by: {{.Release.Service}}
    helm.sh/chart: {{include "app.chart" .}}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{include "app.name" .}}
    app.kubernetes.io/instance: {{.Release.Name}}
