repositories:
  - name: traefik
    url: https://helm.traefik.io/traefik
  - name: jetstack
    url: https://charts.jetstack.io
  - name: datadog
    url: https://helm.datadoghq.com

releases:
  - name: metrics-server
    namespace: kube-system
    chart: charts/metrics-server

  # https://github.com/DataDog/helm-charts/tree/master/charts/datadog
  - name: datadog
    namespace: kube-system
    chart: datadog/datadog
    version: 2.19.9
    values:
      - datadog:
          site: {{requiredEnv "DATADOG_SITE"}}
          apiKey: {{requiredEnv "DATADOG_API_TOKEN"}}
          containerExcludeLogs: "kube_namespace:kube-system"
          logs:
            enabled: true
            containerCollectAll: true

  # https://github.com/traefik/traefik-helm-chart/blob/master/traefik
  - name: traefik
    namespace: ingress
    chart: traefik/traefik
    version: 10.1.1
    values:
      - deployment:
          replicas: 3
        service:
          annotations:
            service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
            service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: 10
            service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: 10

  # https://artifacthub.io/packages/helm/cert-manager/cert-manager
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: v1.4.3
    values:
      - installCRDs: true

  - name: cert-issuer
    namespace: cert-manager
    chart: charts/cert-issuer
    needs:
      - cert-manager/cert-manager
    values:
      - acme:
          email: {{requiredEnv "EMAIL"}}
        cloudflare:
          email: {{requiredEnv "EMAIL"}}
          apiToken: {{requiredEnv "CLOUDFLARE_API_TOKEN"}}
