repositories:
  - name: traefik
    url: https://helm.traefik.io/traefik
  - name: jetstack
    url: https://charts.jetstack.io
  - name: datadog
    url: https://helm.datadoghq.com

releases:
  - name: metrics-server
    namespace: kube-system
    chart: charts/metrics-server

  # https://github.com/DataDog/helm-charts/tree/master/charts/datadog
  - name: datadog
    namespace: kube-system
    chart: datadog/datadog
    version: 2.27.7
    values:
      - datadog:
          site: {{requiredEnv "DATADOG_SITE"}}
          apiKey: {{requiredEnv "DATADOG_API_TOKEN"}}
          containerExcludeLogs: "kube_namespace:kube-system kube_namespace:cert-manager"
          logs:
            enabled: true
            containerCollectAll: true

  # https://github.com/traefik/traefik-helm-chart/blob/master/traefik
  - name: traefik
    namespace: ingress
    chart: traefik/traefik
    version: 10.7.1
    values:
      - deployment:
          replicas: 3
          podAnnotations:
            ad.datadoghq.com/traefik.logs: |
              [{
                "source": "traefik",
                "service": "traefik",
                "log_processing_rules": [{
                  "type": "exclude_at_match",
                  "name": "exclude_traefik_ping_requests",
                  "pattern" : "\/ping"
                }]
              }]
        service:
          annotations:
            service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
            service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
            service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "10"
        logs:
          general:
            format: json
            # Logging levels are DEBUG, PANIC, FATAL, ERROR, WARN, and INFO.
            level: ERROR
          access:
            # To enable access logs
            enabled: true
            # By default, logs are written using the Common Log Format (CLF).
            # To write logs in JSON, use json in the format option.
            # If the given format is unsupported, the default (CLF) is used instead.
            format: json
            fields:
              general:
                defaultmode: keep
                names:
                  {}
                  # Examples:
                  # ClientUsername: drop
              headers:
                defaultmode: drop
                names:
                  User-Agent: keep
                  X-Forwarded-For: keep

  # https://artifacthub.io/packages/helm/cert-manager/cert-manager
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: v1.6.1
    values:
      - installCRDs: true

  - name: cert-issuer
    namespace: cert-manager
    chart: charts/cert-issuer
    needs:
      - cert-manager/cert-manager
    values:
      - acme:
          email: {{requiredEnv "EMAIL"}}
        cloudflare:
          email: {{requiredEnv "EMAIL"}}
          apiToken: {{requiredEnv "CLOUDFLARE_API_TOKEN"}}
