repositories:
  - name: traefik
    url: https://helm.traefik.io/traefik
  - name: jetstack
    url: https://charts.jetstack.io

releases:
  - name: metrics-server
    namespace: kube-system
    chart: charts/metrics-server

  - name: traefik
    namespace: ingress
    chart: traefik/traefik
    version: 9.19.2

  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: v1.4.0
    values:
      - installCRDs: true

  - name: cert-issuer
    namespace: cert-manager
    chart: charts/cert-issuer
    needs:
      - cert-manager/cert-manager
    values:
      - acme:
          email: {{requiredEnv "EMAIL"}}
        cloudflare:
          email: {{requiredEnv "EMAIL"}}
          apiToken: {{requiredEnv "CLOUDFLARE_API_TOKEN"}}
