name: Setup Terraform
description: Download and configure Terraform
inputs:
  terraform-version:
    required: true
  tflint-version:
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform-version }}

    - name: Configure Terraform plugin cache
      shell: bash
      run: |
        echo "TF_PLUGIN_CACHE_DIR=$HOME/.terraform.d/plugin-cache" >>"$GITHUB_ENV"
        mkdir --parents "$HOME/.terraform.d/plugin-cache"

    - name: Cache Terraform
      uses: actions/cache@v4
      with:
        path: |
          ~/.terraform.d/plugin-cache
        key: terraform-${{ runner.os }}-${{ hashFiles('**/.terraform.lock.hcl') }}
        restore-keys: |
          terraform-${{ runner.os }}-

    - uses: actions/cache@v4
      name: Cache tflint plugins
      if: inputs.tflint-version != ''
      with:
        path: ~/.tflint.d/plugins
        key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

    - uses: terraform-linters/setup-tflint@v4
      name: InstallTFLint
      if: inputs.tflint-version != ''
      with:
        tflint_version: ${{ inputs.tflint-version }}
