image:
  repository: eu-amsterdam-1.ocir.io/axpksneljs3y/nvd-codes/images
  tag: fba6be5ede7674bdfb63c3ec55e678b209906dfd

container:
  env:
    - name: LOG_LEVEL
      value: "info"
  envFrom:
    - secretRef:
        name: nvd-codes-blog

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.tls: "true"
  path: /
  pathType: Prefix
  tls:
    - hosts:
        - images.nvd.codes
      secretName: nvd-codes-images
  hosts:
    - images.nvd.codes
