image:
  repository: eu-amsterdam-1.ocir.io/axpksneljs3y/nvd-codes/api
  tag: bdec2e0f76c48e34f9be7ea19ddab0cbe148f56d

container:
  env:
    - name: GITHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: nvd-codes-api-secrets
          key: github_token
    - name: LOG_LEVEL
      value: "info"

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.tls: "true"
  path: /
  pathType: Prefix
  tls:
    - hosts:
        - api.nvd.codes
      secretName: nvd-codes-api
  hosts:
    - api.nvd.codes

middleware:
  - name: set-cors-headers
    spec:
      headers:
        accessControlAllowOriginList:
          - "https://nvd.codes"
        accessControlMaxAge: 100
        addVaryHeader: true
