name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  app-test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Use latest yarn
        run: make setup.yarn

      - name: Install Dependencies
        run: make install.yarn

      - name: Lint Code
        run: make check.app

  app-build:
    name: Build
    runs-on: ubuntu-latest
    environment: production
    needs:
      - app-test
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Enable Corepack
        run: corepack enable

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Use latest yarn
        run: make setup.yarn

      - name: Install Dependencies
        run: make install.yarn

      - name: Build blog
        run: make build

      - name: Archive blog
        uses: actions/upload-artifact@v4
        with:
          name: dist-blog
          path: ./dist

  app-deploy:
    name: Deploy production
    runs-on: ubuntu-latest
    environment: production
    needs:
      - app-test
      - app-build
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Use latest yarn
        run: make setup.yarn

      - name: Install Dependencies
        run: make install.yarn

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-central-1
          role-to-assume: ${{ secrets.AWS_ROLE_NAME }}

      - name: Download blog artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-blog
          path: dist

      - name: Deploy
        run: make deploy

  infra-init:
    name: Init Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.2.4

      - name: Lint
        run: make check.infra

      # - name: Init
      #   run: make infra.init
