name: Release

on:
  push:
    branches:
      - main

permissions:
  id-token: write

jobs:
  build:
    name: Test_Build_Release
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Yarn Cache
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install build dependencies
        run: make install.yarn

      - name: Compile dependencies
        run: make build.libs build.apps

      - name: Lint Code
        run: make check

      # - name: Unit Test
      #   run: make test.unit

      - name: Build blog
        run: make build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-central-1
          role-to-assume: ${{ secrets.AWS_ROLE_NAME }}

      - name: Deploy
        run: make deploy
